Work around googletest-1.11 compilation failures
Summary:
Non functional change.

googletest-1.11 (which is in Arch, F36) breaks fizz test compilation under gcc.

Googletest relies on a lot of ADL magic to find the correct printer for a particular value.

On GCC, somehow this breaks when #include'ing a certain combination of headers
(namely folly/OpenSSLPtrTypes.h); the ADL lookup eventually resolves into some
instantiation context that is:

```
In file included from /usr/include/folly/Optional.h:68,
                 from /builddir/build/BUILD/fizz-2021.11.08.00/fizz/record/Types.h:11,
                 from /builddir/build/BUILD/fizz-2021.11.08.00/fizz/crypto/signature/Signature.h:12,
                 from /builddir/build/BUILD/fizz-2021.11.08.00/fizz/protocol/Certificate.h:11,
                 from /builddir/build/BUILD/fizz-2021.11.08.00/fizz/client/PskCache.h:11,
                 from /builddir/build/BUILD/fizz-2021.11.08.00/fizz/client/Actions.h:11,
                 from /builddir/build/BUILD/fizz-2021.11.08.00/fizz/client/ClientProtocol.h:11,
                 from /builddir/build/BUILD/fizz-2021.11.08.00/fizz/client/test/ClientProtocolTest.cpp:12:
/usr/include/folly/Traits.h: In instantiation of 'struct folly::Conjunction<std::is_base_of<std::exception, x509_st>, folly::exception_wrapper::IsRegularExceptionType<x509_st> >':
/usr/include/folly/ExceptionWrapper.h:375:7:   required by substitution of 'template<class Ex, class Ex_, typename std::enable_if<static_cast<bool>(folly::Conjunction<std::is_base_of<std::exception, typename std::decay<_Tp2>::type>, folly::exception_wrapper::IsRegularExceptionType<Ex_> >::value), long int>::type <anonymous> > folly::exception_wrapper::exception_wrapper(Ex&&) [with Ex = const x509_st&; Ex_ = x509_st; typename std::enable_if<static_cast<bool>(folly::Conjunction<std::is_base_of<std::exception, typename std::decay<_Tp2>::type>, folly::exception_wrapper::IsRegularExceptionType<Ex_> >::value), long int>::type <anonymous> = <missing>]'
/usr/include/gtest/gtest-printers.h:211:33:   required by substitution of 'template<class T, class, class> static void testing::internal::internal_stream_operator_without_lexical_name_lookup::StreamPrinter::PrintValue(const T&, std::ostream*) [with T = x509_st; <template-parameter-1-2> = void; <template-parameter-1-3> = <missing>]'
/usr/include/gtest/gtest-printers.h:291:36:   required by substitution of 'template<class T, class Printer, class ... Printers> struct testing::internal::FindFirstPrinter<T, decltype (Printer::PrintValue(declval<const T&>(), nullptr)), Printer, Printers ...> [with T = x509_st; Printer = testing::internal::internal_stream_operator_without_lexical_name_lookup::StreamPrinter; Printers = {testing::internal::ProtobufPrinter, testing::internal::ConvertibleToIntegerPrinter, testing::internal::ConvertibleToStringViewPrinter, testing::internal::RawBytesPrinter, testing::internal::FallbackPrinter}]'
/usr/include/gtest/gtest-printers.h:287:8:   [ skipping 2 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/include/gtest/gtest-printers.h:307:9:   required from 'void testing::internal::PrintWithFallback(const T&, std::ostream*) [with T = x509_st; std::ostream = std::basic_ostream<char>]'
/usr/include/gtest/gtest-printers.h:441:30:   required from 'void testing::internal::PrintTo(const T&, std::ostream*) [with T = x509_st; std::ostream = std::basic_ostream<char>]'
/usr/include/gtest/gtest-printers.h:691:12:   required from 'static void testing::internal::UniversalPrinter<T>::Print(const T&, std::ostream*) [with T = x509_st; std::ostream = std::basic_ostream<char>]'
/usr/include/gtest/gtest-printers.h:617:31:   required from 'void testing::internal::PrintSmartPointer(const Ptr&, std::ostream*, int) [with T = x509_st; Ptr = std::unique_ptr<x509_st, folly::static_function_deleter<x509_st, X509_free> >; <template-parameter-1-3> = void; std::ostream = std::basic_ostream<char>]'
/usr/include/gtest/gtest-printers.h:624:25:   required from 'void testing::internal::PrintTo(const std::unique_ptr<_Tp, _Dp>&, std::ostream*) [with T = x509_st; D = folly::static_function_deleter<x509_st, X509_free>; std::ostream = std::basic_ostream<char>]'
/usr/include/gtest/gtest-printers.h:691:12:   required from 'static void testing::internal::UniversalPrinter<T>::Print(const T&, std::ostream*) [with T = std::unique_ptr<x509_st, folly::static_function_deleter<x509_st, X509_free> >; std::ostream = std::basic_ostream<char>]'
/usr/include/gmock/gmock-spec-builders.h:1388:31:   required from 'void testing::internal::ActionResultHolder<T>::PrintAsActionResult(std::ostream*) const [with T = std::unique_ptr<x509_st, folly::static_function_deleter<x509_st, X509_free> >; std::ostream = std::basic_ostream<char>]'
/usr/include/gmock/gmock-spec-builders.h:1385:8:   required from here
/usr/include/folly/Traits.h:544:8: error: 'value' is not a member of 'std::is_base_of<std::exception, x509_st>'
  544 | struct Conjunction<T, TList...>
      |        ^~~~~~~~~~~~~~~~~~~~~~~~
```

which leads to some type query of x509_st itself (which is opaque).

Clang does not exhibit this issue, which likely indicates a difference in compiler behavior w.r.t ADL lookup, since this instanation context would not be reached by any other means.

I frankly have no idea why this is the case.

Work around this problem by avoiding `using namespace folly` and using fully qualified lookups instead. Fewer things are brought into the global namespace and this somehow avoids this error. ¯\_(ツ)_/¯

Fixes https://github.com/facebookincubator/fizz/issues/66

Reviewed By: michel-slm

Differential Revision: D32566061

fbshipit-source-id: 5e22be1cf05036c079d51b5c7019481a20d499eb