Fix Windows builds
Summary:
Building fizz on Windows can fail with the following error:

  ...\fizz\server\ServerProtocol.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj

Work around this error by following the message's advice: compile with /bigobj. This makes the fizz library successfully build on Windows.

Unrelatedly, building fizz' tests on Windows fails with the following error:

  cl : Command line error D8021: invalid numeric argument '/Wno-inconsistent-missing-override'

Fix this error by only not giving MSVC the -Wno-inconsistent-missing-override switch. This makes most of fizz' tests successfully build on Windows.

Reviewed By: reanimus

Differential Revision: D13965758

fbshipit-source-id: 5dd19207e59adc37773679da0abcc0038284f742