Move -DFIZZ_HAVE_OQS flag select to :config target
Summary:
Not all targets that use the `FIZZ_HAVE_OQS` flag actually have `backend_openssl` as a dependency. One such example is `FizzThriftProcessor.cpp`:

```
arc deppy explain-dep --from-target fbcode//proxygen/facebook/lib/utils:fizz_thrift_processor --to-target fbcode//fizz/backend:openssl
...
Error: fbcode//fizz/backend:openssl does not exist or is not reachable from fbcode//proxygen/facebook/lib/utils:fizz_thrift_processor
```

Hence, move the flag to the `:config` target which is included by all fizz users.

Reviewed By: zalecodez

Differential Revision: D58299754

fbshipit-source-id: b82206a81572690e2ba719f6c6530f957597e107